version: "3"
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  pyrpg:
    image: crashzeus/pyrpg:dev
    # build: .
    container_name: pyrpg
    tty: true
    networks:
      - net
